apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
  lables:
    app: $APP_NAME
spec: 
  replicas: 2
  selector:
    matchLabels: 
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      imagePullSecrets:
      - name: docker-hub-authentication
      containers:
      - name: $APP_NAME
        image: $DOCKER_REPO:$IMAGE_NAME
        imagePullPolicy: always 
        ports:
        - containerPort: 8080

        